controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robotiq_gripper_controller:
      type: forward_command_controller/ForwardCommandController

    robotiq_gripper_action_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robotiq_gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
    interface_name: position

robotiq_gripper_action_controller:
  ros__parameters:
    default: true
    joint: finger_joint
    allow_stalling: true